export const SET_LOADING = 'SET_LOADING';
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS';
export const FETCH_RECIPE_SUCCESS = 'FETCH_RECIPE_SUCCESS';
export const FETCH_FAILURE = 'FETCH_FAILURE';
export const SEARCH_RECIPE = 'SEARCH_RECIPE';
export const SELECTED_RECIPE = 'SELECTED_RECIPE';
