export const SET_LOADING = 'SET_LOADING';
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS';
export const FETCH_RECIPES_FAILURE = 'FETCH_RECIPES_FAILURE';
export const SEARCH_RECIPE = 'SEARCH_RECIPE';
export const BACK_HOME = 'BACK_HOME';
export const SELECTED_RECIPE = 'SELECTED_RECIPE';
